### ISSUE TITLE
python ic4 library Grabber.is_streaming property not working

### ISSUE THREAD

**Issue by palec87** [TheImagingSource/ic4-examples#1]
When checking is_streaming property, followig pops

File "......site-packages\imagingcontrol4\grabber.py", line 257, in is_streaming
    return Library.core.ic4_grabber_is_streaming()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: this function takes at least 1 argument (0 given)

OS: Windows11
Python 3.11

**Comment by TIS-Tim** [comment]
Thank you for the bug report!

Should be fixed with the updated version on pypi (1.0.1.2418).

**Comment by palec87** [comment]
Sorry for late response. In deed the 1.0.1.2418 version works for me. I am closing the issue.
