### ISSUE TITLE
Pose calibration between AR glasses and eye mimicking cameras

### ISSUE THREAD

**Issue by yutonglab** [TheImagingSource/ic4-examples#20]
Dears,
I have a calibration requirement for AR glasses and a human eye like camera. The details of the requirement are as follows：AR glasses and binocular eye mimicking cameras are placed on a fixed bracket. The binocular eye mimicking cameras look straight ahead like the human eye, and the AR glasses is located in front of the eye mimicking cameras, the center of each camera is about 2-3cm away from the center of the AR glasses lens, which is similar to the positional relationship of the human eye wearing AR glasses. How to calibrate the relationship between eye mimicking cameras and AR glasses? I am looking forward to your advice. Thank you!

**Comment by TIS-Tim** [comment]
Am I missing something, or is this totally off-topic?

**Comment by yutonglab** [comment]
很高兴收到您的邮件！祝您工作顺利，生活愉快！
