### ISSUE TITLE
Linking of IC4 drivers under Windows

### ISSUE THREAD

**Issue by kparent60** [TheImagingSource/ic4-examples#27]
Hi TIS team,

I have an issue with how the Windows OS interact with the newest USB3 IC4 drivers. I used the link on your [website](https://www.theimagingsource.com/en-us/support/download/ic4gentlprodu3vwintis-1.3.1.501/) to get the Windows .msi to download the drivers. The installation went well and my already connected cameras are working correctly with this new driver.

My issue here is, whenever I connect a new type of TIS camera, Windows doesn't auto link it to the IC4 driver. I have to manually remove the IC4 drivers with the same .msi file, and reinstall it so it gets recognized correctly in Windows device manager as 'The Imaging Source Europe GmbH GenTL-U3V Camera'. Otherwise, it would show as 'USB3 device (unused)' [something like that I don't have the precise name on hands right now].

One thing I might suspect is the fact that, previously, we used those cameras on this computer with the previous drivers (non IC4), so in the device manager they appear as 'The Imaging Source Europe GmbH DMK 33UX249'. This one is recognized correctly by Windows.

So I have 2 questions here :

1. Is there any potential issue to have both drivers shown in Device manager at the same time? Should we only keep one, maybe by uninstalling the other one?
2. What should I do whenever I connect a new camera so the IC4 driver gets linked correctly under Windows?

Thank you in advance,
Keven

**Comment by kparent60** [comment]
Hi Stephan,

Damn you're fast on your responses x)

Ok so if I understanding correctly, since they use a different interface, there should be no interference between them even though they communicate to the same hardware?

I will try the update from device manager next time it happens.

Thank you,
Keven

**Comment by TIS-Tim** [comment]
Hi Keven,

if Windows keeps selecting the wrong driver for the U3V interface, you could also entirely delete the "(unused)" driver (which the 5.x driver installs just to get rid of warning in device manager).

To do that, press delete once you selected the entry in device manager, and, in the confirmation dialog, check the checkbox to delete the driver from the system. The automatic selection should then always choose ic4 driver.

Tim

**Comment by kparent60** [comment]
Hi Tim,

Perfect thank you, will try that next time it happens!

Keven
