### ISSUE TITLE
PropId.ExposureMode does not exist ?

### ISSUE THREAD

**Issue by 5CoJL** [TheImagingSource/ic4-examples#9]
Hello,

I'm having a problem trying to set up an ExposureMode at TriggerWidth. That is, I can't seem to find the ExposureMode PropId, nor in the lib or the docs.

Yet, that is a tweakable setting in IC Capture 2.5...

Am I missing something ?

**Comment by TIS-Tim** [comment]
Hello,

the GenICam SFNC-compliant way to enable this feature is via `TriggerSelector`:

```
TriggerSelector := ExposureActive
TriggerMode := On
```

**Comment by 5CoJL** [comment]
Ah I see, sorry for the lack of knowledge on the subject.

I was reading the SNFC diagonally and based on chapter 5.7 I hastily linked TriggerWidth of IC Capture with that ExposureMode property.

Many thanks !

**Comment by TIS-Tim** [comment]
No worries!

IC Capture does many things a little differently, due to a lack of support for UI for these selector-type properties.
